### PR TITLE
Fixes #6, bulk_streaming errors logged instead of raised.

### LINKED ISSUE #6: BulkIndexError needs to be caught in bulk_upsert
See https://github.com/mongodb-labs/mongo-connector/issues/482 for details.

### PR DESCRIPTION
**Pull request by estobbart**

### CODE REVIEW

**Comment by estobbart** [comment]
@llvtt

**Comment by llvtt** [comment]
I made a comment about this approach here: https://github.com/mongodb-labs/elastic2-doc-manager/issues/6#issuecomment-231144595. Would you mind revising this to use the Exception wrapper? I must have missed this PR when I made my comment in #6.

**Comment by p-backman-ericsson** [comment]
Hello @estobbart ! Any plans to revise the patch based on the comment from @llvtt ?

**Comment by estobbart** [comment]
@p-backman-ericsson I've actually been using this version, and it's held up. Are you seeing something different? I can revisit, but it looked like the original intention was to capture it at the level it's at now, and that the flag was missed in the call.

**Comment by p-backman-ericsson** [comment]
@estobbart I also think it works but @llvtt asked (see comment above) if you could do it another way using the Exception wrapper. Could you give him a response on that? I guess that is the reason this pull request has not been merged.

**Comment by ShaneHarvey** [comment]
I'm closing this because we decided to handle BulkIndexErrors using another approach (#14).

**Pull request closed without merging**
